config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :constituencies
  resources :contests
  resources :politicians
  mount Ckeditor::Engine => '/ckeditor'
  resources :parties
  resources :persons
  resources :counties
  resources :coalitions
  resources :coalitions
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  
  resources :debates do
    member do
      put "upvote", to: "debates#upvote"
      put "downvote", to: "debates#downvote"
    end
  end
  resources :bills do
    member do
      put "upvote", to: "bills#upvote"
      put "downvote", to: "bills#downvote"
    end
  end
  
  get 'about' => 'static#about', as: :about
  get 'privacy' => 'static#privacyandlegal', as: :privacy
  root 'home#index'
end

app/models/party.rb
class Party < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
	belongs_to :coalition
	has_many :politicians
	
	def politicians
    	Politician.where(:party_id => self.id).to_a 
  	end

  	#create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
	def to_param
	  "#{id} #{name}".parameterize
	end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
    @politicians = Politician.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @politicians = Politician.all
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name, :founded, :abbrev, :coalition_id, :avatar)
    end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_for @party, html: { multipart: true } do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
   <div class="field">
    <%= image_tag @party.avatar.url(:thumb) %>
  </div>
  
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.date_select :founded %>
  </div>
  <div class="field">
    <%= f.label :abbrev %><br>
    <%= f.text_field :abbrev %>
  </div>
  
  <div class="field">
    <%= f.label :Coalition %><br>
    <%= f.collection_select :coalition_id, Coalition.all, :id, :abbrev %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>
<h4>Listing parties</h4>

<div class="container" style="margin-top:20px;">
  <div class="row">
     <% @parties.each do |party| %>
    <div class="col-lg-10">
      <div class="media">
        <a href="#" class="pull-left"> 
          <%= image_tag party.avatar.url(:thumb), class: "avatar-thumb media-object img-thumbnail" %>
          <!--<img alt="64x64" data-src="holder.js/64x64" class="media-object img-thumbnail" style="width: 64px; height: 64px;" src="http://placehold.it/64x64">      -->
        </a>
        <div class="media-body">
          <h3 class="media-heading">
            <strong><%= link_to (party.name), party %></strong>
          </h3>
          <p class="">Member of <%= link_to (party.coalition.abbrev), coalitions_path %> Coalition.</p>
        </div>
      </div>     
    
    </div>
    <% end %>
  </div>
</div>


<div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <%unless user_signed_in? %>
            <div class="modal-content">
               <%= render 'shared/register'%> 
            </div>
          <% end %>
        </div>
      </div>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-10" style="margin:0 auto;">
    <div class="col-sm-6">
      <p>
        <%= link_to 'Back', parties_path, class: "pull-right" %>
      </p>
      <p>
        <%= image_tag @party.avatar.url(:thumb), class: "media-object img-thumbnail" %>
      </p>
      
      <p>
        <strong>Name:</strong>
        <%= @party.name %>
      </p>
      
      <p>
        <strong>Founded:</strong>
        <%= @party.founded %>
      </p>
      
      <p>
        <strong>Abbrev:</strong>
        <%= @party.abbrev %>
      </p>
      
      <p>
        <strong>Coalition:</strong>
        <%= link_to Coalition.find(@party.coalition_id).name, coalition_path(@party.coalition_id) %>
      </p>
      
      <!-- <%#= link_to 'Edit', edit_party_path(@party) %> |
      <%#= link_to 'Back', parties_path %> -->
    </div>
    
    <div class="col-sm-6">
      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Politicians</a></li>
        <li><a data-toggle="tab" href="#menu1">Parties</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
          <h3>Politicians</h3>
          <p>Politicians in This Party</p>
          <div class="row">
            <% @party.politicians.each do |politician| %>
              <div class="col-lg-6">
                <div><%= image_tag politician.avatar.url(:thumb), class: "media-object img-thumbnail" %></div>
                <div><%= link_to (truncate(politician.full_name, :length => 16, separator: ' ', :escape => false)), politician %></div>
          <div>Position <%= link_to Contest.find(politician.contest_id).name, contest_path(politician.contest_id) %></div>
                <div> County <%= link_to County.find(politician.county_id).name, county_path(politician.county_id) %></div>
              </div>
            <% end %>
          </div>
        </div>
        <div id="menu1" class="tab-pane fade">
          <h3>Parties</h3>
          
          <p>Parties in this Coalition</p>
          <p>
            
          </p>
        </div>
      </div>
    </div>
  </div>
</div>