config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :constituencies
  resources :contests
  resources :politicians
  mount Ckeditor::Engine => '/ckeditor'
  resources :parties
  resources :persons
  resources :counties
  resources :coalitions
  resources :coalitions
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  
  resources :debates do
    member do
      put "upvote", to: "debates#upvote"
      put "downvote", to: "debates#downvote"
    end
  end
  resources :bills do
    member do
      put "upvote", to: "bills#upvote"
      put "downvote", to: "bills#downvote"
    end
  end
  
  get 'about' => 'static#about', as: :about
  get 'privacy' => 'static#privacyandlegal', as: :privacy
  root 'home#index'
end

app/models/bill.rb
class Bill < ActiveRecord::Base
	validates :user_id, presence: true

	has_attached_file :document, styles: {:thumbnail => ["200x160>", :png], :medium => ["250x250>"]}
    validates_attachment :document, content_type: { :content_type => ["image/jpg", "image/jpeg", "image/png", "application/pdf"]}
   
	acts_as_votable
	acts_as_commentable
	  
	belongs_to :politician
	belongs_to :user

	#create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
	def to_param
	   "#{id} #{title}".parameterize
	end


end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :debates
end

app/models/coalition.rb
class Coalition < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
	has_many :parties
	has_many :politicians

	belongs_to :user
	
	def politicians
    Politician.where(:coalition_id => self.id).to_a 
  end
  	
  def parties
    Party.where(:coalition_id => self.id).to_a 
  end

  #create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
  def to_param
    "#{id} #{name}".parameterize
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
	belongs_to :county

	#create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
	def to_param
	  "#{id} #{name}".parameterize
	end
end

app/models/contest.rb
class Contest < ActiveRecord::Base
    has_many :politicians

  def politicians
    Politician.where(:coalition_id => self.id).to_a 
  end

  #create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
	def to_param
	  "#{id} #{name}".parameterize
	end
end

app/models/county.rb
class County < ActiveRecord::Base
	has_many :constituencies
	has_many :politicians
	has_many :users
	
	def constituencies
    	Constituency.where(:county_id => self.id).to_a 
  	end
  	
  	def politicians
    	Politician.where(:county_id => self.id).to_a 
  	end

    #create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
  def to_param
    "#{id} #{name}".parameterize
  end
end

app/models/debate.rb
class Debate < ActiveRecord::Base
	#before_action :authenticate_user!

	validates :user_id, presence: true
	belongs_to :category
	belongs_to :user

	acts_as_votable
	acts_as_commentable
end

app/models/party.rb
class Party < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
	belongs_to :coalition
	has_many :politicians
	
	def politicians
    	Politician.where(:party_id => self.id).to_a 
  	end

  	#create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
	def to_param
	  "#{id} #{name}".parameterize
	end
end

app/models/politician.rb
class Politician < ActiveRecord::Base
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/image.svg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    has_many :bills
    
    belongs_to :coalition
    belongs_to :county
    belongs_to :party
    
    belongs_to :contest 
    
    def bills
    	Bill.where(:politician_id => self.id).to_a 
    end

    #create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
    def to_param
      "#{id} #{full_name}".parameterize
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/image.svg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  belongs_to :county
  has_many :bills
  has_many :coalitions
  has_many :debates
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  attr_accessor :login
  
  # Only allow letter, number, underscore and punctuation.
  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
  
  #create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
  def to_param
    "#{id} #{username}".parameterize
  end

  def user_params
      params.require(:user).permit(:avatar)
  end

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/shared/_footer.html.erb
<div class="clearfix" style="margin-top:100px;"></div>
<div class="footer">
		<div class="container">
			<div class="footer-row">
				<div class="col-md-4 footer-grids">
					<h4><a href="index.html">Uwazi <br><span>Citizens in Legislature</span></a></h4>
					<p> +254 723 833 525</p>
					<p>+254 703 597 595 </p>
					<ul class="social-icons">
						<li><a href="https://www.facebook.com/UwaziKE/" target="_blank"><i class="fa fa-facebook"></i></a></li>
						<li><a href="https://twitter.com/uwazike" target="_blank"><i class="fa fa-twitter"></i></a></li>
					</ul>
				</div>
				<div class="col-md-3 footer-grids">
					<h3>Navigation</h3>					
					<ul>
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "About Us", about_path %></li>
						<li><%= link_to "Contact" %></li>
					</ul>
				</div>
				<div class="col-md-2 footer-grids">
					<h3>Support</h3>
					<ul>
						<li><%= link_to "Volunteer" %></li>
						<li><%= link_to "Help Center" %></li>
					</ul>
				</div>
				<div class="col-md-2 footer-grids">
					<h3>Contact us</h3>
					<ul>
						<li>4<sup>th</sup> Floor, Bishop Magua Center.</li>
						<li>Ngong Rd, Nairobi</li>
						<li><a href="mailto:info@uwazi.or.ke">info@uwazi.or.ke</a></li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Uwazi", root_url, class: "navbar-brand" %>
     
    </div>
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Bills', bills_path %></li>
        <li><%= link_to 'Politicians', politicians_path %></li>
        <li><%= link_to 'Parties', parties_path %></li>
        <li><%= link_to 'Debates', debates_path %></li>
        <li><%= link_to 'Counties', counties_path %></li>
        <li><%= link_to 'About', about_path  %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to (current_user.username), edit_user_registration_path %></li>
          <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><a href="#", data-toggle="modal" data-target="#myModal">Sign in </a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<!-- Modal -->
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <%unless user_signed_in? %>
            <div class="modal-content">
               <%= render 'shared/register'%> 
            </div>
          <% end %>
        </div>
      </div>

app/views/shared/_register.html.erb
<h2>Log In</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>