config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :constituencies
  resources :contests
  resources :politicians
  mount Ckeditor::Engine => '/ckeditor'
  resources :parties
  resources :persons
  resources :counties
  resources :coalitions
  resources :coalitions
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  
  resources :debates do
    member do
      put "upvote", to: "debates#upvote"
      put "downvote", to: "debates#downvote"
    end
  end
  resources :bills do
    member do
      put "upvote", to: "bills#upvote"
      put "downvote", to: "bills#downvote"
    end
  end
  
  get 'about' => 'static#about', as: :about
  get 'privacy' => 'static#privacyandlegal', as: :privacy
  root 'home#index'
end

app/models/debate.rb
class Debate < ActiveRecord::Base
	#before_action :authenticate_user!

	validates :user_id, presence: true
	belongs_to :category
	belongs_to :user

	acts_as_votable
	acts_as_commentable
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_debate, only: [:show, :edit, :update, :destroy]

  # GET /debates
  # GET /debates.json
  def index
    @debates = Debate.all
  end

  # GET /debates/1
  # GET /debates/1.json
  def show
    @debate = Debate.find(params[:id])
    @new_comment = Comment.build_from(@debate, 1, "")
  end

  # GET /debates/new
  def new
    @debate = current_user.debates.build
  end

  # GET /debates/1/edit
  def edit
  end


  def upvote
    @debate = Debate.find(params[:id])
    @debate.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @debate = Deabte.find(params[:id])
    @debate.downvote_by current_user
    redirect_to :back
  end

  # POST /debates
  # POST /debates.json
  def create
    @debate = current_user.debates.build(debate_params)

    respond_to do |format|
      if @debate.save
        format.html { redirect_to @debate, notice: 'Debate was successfully created.' }
        format.json { render :show, status: :created, location: @debate }
      else
        format.html { render :new }
        format.json { render json: @debate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debates/1
  # PATCH/PUT /debates/1.json
  def update
    respond_to do |format|
      if @debate.update(debate_params)
        format.html { redirect_to @debate, notice: 'Debate was successfully updated.' }
        format.json { render :show, status: :ok, location: @debate }
      else
        format.html { render :edit }
        format.json { render json: @debate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debates/1
  # DELETE /debates/1.json
  def destroy
    @debate.destroy
    respond_to do |format|
      format.html { redirect_to debates_url, notice: 'Debate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debate
      @debate = Debate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debate_params
      params.require(:debate).permit(:title, :category_id, :user_id)
    end
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/views/debates/_form.html.erb
<%= form_for(@debate) do |f| %>
  <% if @debate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debate.errors.count, "error") %> prohibited this debate from being saved:</h2>

      <ul>
      <% @debate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :Category %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debates/edit.html.erb
<h1>Editing Debate</h1>

<%= render 'form' %>

<%= link_to 'Show', @debate %> |
<%= link_to 'Back', debates_path %>

app/views/debates/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Create a New Debate', new_debate_path %>

<h1>Listing Debates</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @debates.each do |debate| %>
      <tr>
        <td><%= link_to debate.title, debate %><br> 

         <div class="btn-group">
          <button type="button" class="btn btn-success"><%= debate.get_upvotes.size %> <span class="fa fa-thumbs-o-up"> Support</span></button>
          <button type="button" class="btn btn-warning"><%= debate.get_downvotes.size %> <span class="fa fa-thumbs-o-down"> Oppose</span></button>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/debates/new.html.erb
<h1>New Debate</h1>

<%= render 'form' %>

<%= link_to 'Back', debates_path %>

app/views/debates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Category:</strong>
	<%= link_to Category.find(@debate.category_id).name, category_path(@debate.category_id) %>
</p>
<p>
  <strong>Title:</strong>
  <%= @debate.title %>
</p>

<p>
	<% if user_signed_in? %>
	<div class="btn-group">
		Still in development<br>
          <button type="button" class="btn btn-success"><%= @debate.get_upvotes.size %> <span class="fa fa-thumbs-o-up"> Support</span></button>
          <button type="button" class="btn btn-warning"><%= @debate.get_downvotes.size %> <span class="fa fa-thumbs-o-down"> Oppose</span></button>
        </div>

            <p>
              <%= link_to upvote_debate_path(@debate), method: :put do %>
                Support
                <%= @debate.get_upvotes.size %>
              <% end %>
              | <%= link_to downvote_debate_path(@debate), method: :put do %>
                Oppose
                <%= @debate.get_downvotes.size %>
              <% end %>
            </p>
    <% end %>
</p>

<%= link_to 'Edit', edit_debate_path(@debate) %> |
<%= link_to 'Back', debates_path %>

<div class="">
  <%= render partial: "comments/template", locals: {commentable: @debate, new_comment: @comment} %>
</div>

<div class="clearfix"></div>