config/routes.rb
Rails.application.routes.draw do
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :constituencies
  resources :contests
  resources :politicians
  mount Ckeditor::Engine => '/ckeditor'
  resources :parties
  resources :persons
  resources :counties
  resources :coalitions
  resources :coalitions
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  
  resources :debates do
    member do
      put "upvote", to: "debates#upvote"
      put "downvote", to: "debates#downvote"
    end
  end
  resources :bills do
    member do
      put "upvote", to: "bills#upvote"
      put "downvote", to: "bills#downvote"
    end
  end
  
  get 'about' => 'static#about', as: :about
  get 'privacy' => 'static#privacyandlegal', as: :privacy
  root 'home#index'
end

app/models/politician.rb
class Politician < ActiveRecord::Base
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/image.svg"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
    has_many :bills
    
    belongs_to :coalition
    belongs_to :county
    belongs_to :party
    
    belongs_to :contest 
    
    def bills
    	Bill.where(:politician_id => self.id).to_a 
    end

    #create pretty urls by overiding the  to_param .. find out why the gem is better. only change then
    def to_param
      "#{id} #{full_name}".parameterize
    end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_politician, only: [:show, :edit, :update, :destroy]

  # GET /politicians
  # GET /politicians.json
  def index
    @politicians = Politician.all
  end

  # GET /politicians/1
  # GET /politicians/1.json
  def show
  end

  # GET /politicians/new
  def new
    @politician = Politician.new
  end

  # GET /politicians/1/edit
  def edit
  end

  # POST /politicians
  # POST /politicians.json
  def create
    @politician = Politician.new(politician_params)

    respond_to do |format|
      if @politician.save
        format.html { redirect_to @politician, notice: 'Politician was successfully created.' }
        format.json { render :show, status: :created, location: @politician }
      else
        format.html { render :new }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politicians/1
  # PATCH/PUT /politicians/1.json
  def update
    respond_to do |format|
      if @politician.update(politician_params)
        format.html { redirect_to @politician, notice: 'Politician was successfully updated.' }
        format.json { render :show, status: :ok, location: @politician }
      else
        format.html { render :edit }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicians/1
  # DELETE /politicians/1.json
  def destroy
    @politician.destroy
    respond_to do |format|
      format.html { redirect_to politicians_url, notice: 'Politician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      @politician = Politician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politician_params
      params.require(:politician).permit(:county_id, :coalition_id, :party_id, :avatar, :contest_type, :contest_id, :full_name, :primary_secondary_school, :undergraduate_school, :graduate_school, :previous_position, :born, :telephone, :web, :description, :email)
    end
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/views/politicians/_form.html.erb
<%= form_for @politician, html: { multipart: true } do |f| %>
  <% if @politician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@politician.errors.count, "error") %> prohibited this politician from being saved:</h2>

      <ul>
      <% @politician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= image_tag @politician.avatar.url(:medium), class:"avatar-thumb" %>
  </div>
  
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :born %><br>
    <%= f.date_select :born %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <!-- <div class="field">
    <%= f.label :Contest %><br>
    <%= f.text_field :contest_type %>
  </div> -->
  <div class="field">
    <%= f.label :Position %><br>
    <%= f.collection_select :contest_id, Contest.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :Party %><br>
    <%= f.collection_select :party_id, Party.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :County %><br>
    <%= f.collection_select :county_id, County.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :Coalition %><br>
    <%= f.collection_select :coalition_id, Coalition.all, :id, :abbrev %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.cktext_area :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/politicians/edit.html.erb
<h1>Editing Politician</h1>

<%= render 'form' %>

<%= link_to 'Show', @politician %> |
<%= link_to 'Back', politicians_path %>

app/views/politicians/index.html.erb
<p id="notice"><%= notice %></p>
<h4>Listing Politicians</h4>

<div class="container" style="margin-top:20px;">
  <div class="row">
     <% @politicians.each do |politician| %>
    <div class="col-lg-10">
      <div class="media">
        <a href="#" class="pull-left"> 
          <%= image_tag politician.avatar.url(:thumb), class: "avatar-thumb media-object img-thumbnail" %>
          <!--<img alt="64x64" data-src="holder.js/64x64" class="media-object img-thumbnail" style="width: 64px; height: 64px;" src="http://placehold.it/64x64">      -->
        </a>
        <div class="media-body">
          <h3 class="media-heading">
            <strong><%= link_to (politician.full_name), politician %></strong>
          </h3>
          <p class=""><%= link_to Contest.find(politician.contest_id).name, contest_path(politician.contest_id) %> for <%= link_to County.find(politician.county_id).name, county_path(politician.county_id) %>.</p>
          <p class="capitalize">Member of <%= link_to Party.find(politician.party_id).name, party_path(politician.party_id) %>.</p>
        </div>
      </div>     
    
    </div>
    <% end %>
  </div>
</div>


<div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <%unless user_signed_in? %>
            <div class="modal-content">
               <%= render 'shared/register'%> 
            </div>
          <% end %>
        </div>
      </div>
      
      

app/views/politicians/new.html.erb
<h1>New Politician</h1>

<%= render 'form' %>

<%= link_to 'Back', politicians_path %>

app/views/politicians/show.html.erb
<section id="about" class="scroll-section root-sec grey lighten-5 about-wrap">
      <div class="container">
        <div class="row">
          <div class="clearfix about-inner">
            <div class="col-sm-6 col-md-4">
              <h3 class="about-subtitle"><%= @politician.full_name %></h3>
              <div style="visibility: visible; animation-name: fadeIn;" class="person-img wow fadeIn animated animated">
                <%= image_tag @politician.avatar.url(:medium), class: " z-depth-1" %>
                <!--<img class="z-depth-1" src="images/person.jpg" alt="">-->
              </div>
              <div class="about-social">
                <ul>
                  <li>
                    <a href="#" class="btn-floating waves-effect waves-light white"><i class="fa fa-facebook"></i></a>
                  </li>
                  <li>
                    <a href="#" class="btn-floating waves-effect waves-light white"><i class="fa fa-twitter"></i></a>
                  </li>
                  <li>
                    <a href="<%= @politician.email %>" class="btn-floating waves-effect waves-light white"><i class="fa fa-envelope"></i></a>
                  </li>
                  <li>
                     <a href="<%= @politician.web %>" class="btn-floating waves-effect waves-light white" target="_blank"><i class="fa fa-chain"></i></a>
                  </li>
                </ul>
              </div>
              <div>
                <%= link_to 'Back', politicians_path, class: "pull-right" %>
                <%#= link_to 'Edit', edit_politician_path(@politician) %> |
                <%#= link_to 'Back', politicians_path %>
              </div>
            </div>
            <!-- about me image -->

            <div class="col-sm-6 col-md-4">
              <div class="person-info">
                <h3 class="about-subtitle">Personal Information</h3>
                <h5><span>Born :</span> <%= @politician.born.strftime(" %d %b, %Y ") %></h5>
                <h5><span>Phone :</span> <%= @politician.telephone %></h5>
                <h5><span>Position :</span> 
                  <%= link_to Contest.find(@politician.contest_id).name, contest_path(@politician.contest_id) %></h5>
                <h5><span>County :</span>
                <%= link_to County.find(@politician.county_id).name, county_path(@politician.county_id) %></h5>
                <h5><span>Party :</span> 
                <%= link_to Party.find(@politician.party_id).name, party_path(@politician.party_id) %></h5>
                <h5><span>Coalition :</span> 
                <%= link_to Coalition.find(@politician.coalition_id).abbrev, coalition_path(@politician.coalition_id) %></h5>
                <h5><span>Primary &amp; Secondary :</span> <%= @politician.primary_secondary_school %></h5>
                <h5><span>Undergraduate :</span> <%= @politician.undergraduate_school %></h5>
                <h5><span>Graduate School :</span> <%= @politician.graduate_school %></h5>
                
              </div>

              
            </div>
            <!-- about me info -->
            
            <div class="col-sm-12 col-md-4">
              <div class="person-about">
                <h3 class="about-subtitle">My Story</h3>
                <%= raw(@politician.description) %>
                <!--<a class="waves-effect waves-light btn-large brand-bg white-text"><i class="mdi-content-archive left"></i> Download Resume</a>-->
              </div>
            </div>

          </div>
        </div>
      </div>
      <!-- .container end -->
    </section>
    <div>
      <p class="capitalize">Bills By <%= @politician.full_name %></p>
      <p>
        <% @politician.bills.each do |bill| %>
          <div><%= link_to (bill.title), bill %></div>
        <% end %>
      </p>
    </div>
    